CREATE DATABASE Minion
USE Minion

CREATE TABLE Minion
(
	Id INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	Age TINYINT,
)

CREATE TABLE Towns
(
	Id INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
)